server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t \"%r\" %s %b"
    basedir: .
  forward-headers-strategy: framework

logging:
  level:
    org.apache.coyote.http11: INFO
    org.apache.tomcat.util.net: INFO

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

game:
  match:
    token-secret: YBHft+TFtCj6J2Em9wafFGeTK6AHNzYvcznuyNELIo2u9mRWqawmkuFhwfVIRuME7NYSjQHyCF4nsPXCv92d5A==
    token-ttl-seconds: 3600